Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Exclude:
      - "test/**/*"
Metrics/MethodLength:
  Exclude:
      - "test/**/*"
Metrics/ClassLength:
  Exclude:
      - "test/**/*"
AllCops:
    NewCops: enable
    Exclude:
      - ".irb_history"
