CREATE TABLE notes (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    text text, position integer NOT NULL,
                    updated_at timestamp NOT NULL DEFAULT NOW());
